version: '3'
services:
  portfolio:
    build: 
      context: .
    image: ghcr.io/ymmmtym/portfolio
    container_name: portfolio
    hostname: portfolio
    tty: true
    ports:
      - "8080:80"
    # volumes:
    #   - .:/app
    #   - /app/node_modules
