version: '3'
services:
    portfolio:
        build: .
        container_name: portfolio
        hostname: portfolio
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./app:/app
