version: '3'
services:
    portfolio:
        build: .
        container_name: portfolio
        hostname: portfolio
        tty: true
        ports:
            - "8080:8080"
        volumes:
            - ./app:/root/app
            - /app/node_modeles