version: 2.1
executors:
  default:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
          working_directory: app
      - run:
          name: 'Install Dependecies'
          command: yarn add firebase-tools
          working_directory: app
      - run:
          name: build
          command: yarn build
          working_directory: app
      - run:
          name: 'Deploy to Hosting'
          command: node_modules/.bin/firebase deploy --only hosting:portfolio --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
          working_directory: app
  deploy:
    executor: default
    steps:
      - checkout
      - run:
        name: 'Deploy to Hosting'
        command: node_modules/.bin/firebase deploy --only hosting:portfolio --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
        working_directory: app


workflows:
  version: 2
  test:
    jobs:
      - build:
      - deploy: 
          filters:
            branches:
              only: production