version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: build
          command: npm run build
      # - run:
      #     name: deploy to Firebase Hosting
      #     command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy:
          filters:
            branches:
              only: master