version: 2.1
executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: list
          command: ls

workflows:
  version: 2
  deploy_dev:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy:
          filters:
            branches:
              only: master
