version: 2.1
executors:
  default:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
          working_directory: app
      - run:
          name: 'Install Dependecies'
          command: yarn add firebase-tools
      - run:
          name: build
          command: yarn build
      - run:
          name: 'Deploy to Hosting'
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
