version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: 'Install Dependecies'
          command: npm install --save-dev firebase-tools
      - run:
          name: build
          command: npm run build
      - run:
          name: 'Deploy to Hosting'
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy:
          filters:
            branches:
              only: master