version: 2.1
executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
          working_directory: app
      - run:
          name: yarn install
          command: ls
      - run:
          name: test3
          command: ls ~

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
