version: 2.1
executors:
  node:
    docker:
      - image: circleci/node

jobs:
  build:
    executor: node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: test1
          command: pwd
      - run:
          name: test2
          command: ls
              - run:
          name: test3
          command: ls ~

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      # - deploy:
      #     filters:
      #       branches:
      #         only: master
